services:
  - postgres:13.3-alpine

variables:
  POSTGRES_DB: develop
  POSTGRES_USER: acid
  POSTGRES_PASSWORD: password

stages:
  - test

test:
  stage: test
  image: node:lts-alpine
  variables:
    DB_HOST: postgres
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - yarn lint:ci
    - yarn migration:run
    - yarn test
    - yarn test:e2e:db
