version: "3.7"
services:
  db:
    image: mongo:6.0.7-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: acid
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  queue:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: eu-west-1
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: acid
      DB_PASSWORD: password
      DB_DATABASE: develop
      DEPLOY_ENV: dev

    working_dir: /home/node/
    volumes:
      - "./src:/home/node/src"
      - "./test:/home/node/test"
    entrypoint:
      - /bin/sh
      - -c
      - |
        ./entrypoint.sh
    ports:
      - "8080:8080"
    networks:
      - default

